services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: kivi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=kivi
    profiles:
      - backend
      - all

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    profiles:
      - frontend
      - all

volumes:
  db_data: